name: oth_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  dartz: ^0.10.1
  go_router: ^14.3.0
  get_it: ^8.0.1
  connectivity_plus: ^6.1.0
  fluentui_system_icons: ^1.1.260
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  dio: ^5.7.0
  envied: ^0.5.4+1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  gap: ^3.0.1
  cached_network_image: ^3.4.1
  skeletonizer: ^1.4.2
  flutter_hooks: ^0.20.5
  internet_connection_checker_plus: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  envied_generator: ^0.5.4+1
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
